
  CREATE TABLE "DIVINGAPP"."DIVE_SITES" 
   (	"SITE_ID" NUMBER NOT NULL ENABLE, 
	"SITE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"AREA" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" CLOB, 
	"MAX_DEPTH" NUMBER(5,1), 
	"WATER_TEMPERATURE_MIN" NUMBER(4,1), 
	"WATER_TEMPERATURE_MAX" NUMBER(4,1), 
	"DIFFICULTY" VARCHAR2(20), 
	"MARINE_LIFE" VARCHAR2(1000), 
	"ACCESS_INFO" VARCHAR2(500), 
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CK_DS_DIFFICULTY" CHECK (DIFFICULTY IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')) ENABLE, 
	 CONSTRAINT "PK_DIVE_SITES" PRIMARY KEY ("SITE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 