
  CREATE TABLE "DIVINGAPP"."DIVING_LOGS" 
   (	"LOG_ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"SITE_ID" NUMBER, 
	"RESERVATION_ID" NUMBER, 
	"DIVE_DATE" DATE NOT NULL ENABLE, 
	"MAX_DEPTH" NUMBER(5,1), 
	"DIVE_TIME" NUMBER, 
	"WATER_TEMP" NUMBER(4,1), 
	"VISIBILITY" NUMBER(4,1), 
	"WEATHER" VARCHAR2(50), 
	"BUDDY" VARCHAR2(100), 
	"NOTES" CLOB, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_DIVING_LOGS" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_DL_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "DIVINGAPP"."CUSTOMERS" ("CUSTOMER_ID") ENABLE, 
	 CONSTRAINT "FK_DL_SITE" FOREIGN KEY ("SITE_ID")
	  REFERENCES "DIVINGAPP"."DIVE_SITES" ("SITE_ID") ENABLE, 
	 CONSTRAINT "FK_DL_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "DIVINGAPP"."RESERVATIONS" ("RESERVATION_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("NOTES") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 