
  CREATE TABLE "DIVINGAPP"."OPTIONS_MASTER" 
   (	"OPTION_ID" NUMBER NOT NULL ENABLE, 
	"OPTION_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"OPTION_CATEGORY" VARCHAR2(50) NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CK_OM_CATEGORY" CHECK (OPTION_CATEGORY IN ('RENTAL', 'TRANSPORT', 'PHOTO', 'INSURANCE', 'OTHER')) ENABLE, 
	 CONSTRAINT "PK_OPTIONS_MASTER" PRIMARY KEY ("OPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 