
  CREATE TABLE "DIVINGAPP"."REPORT_CACHE" 
   (	"CACHE_ID" NUMBER NOT NULL ENABLE, 
	"REPORT_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"SECTION" VARCHAR2(50) NOT NULL ENABLE, 
	"REPORT_DATE" DATE, 
	"METRIC_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"METRIC_VALUE" NUMBER(15,2), 
	"DIMENSION1" VARCHAR2(200), 
	"DIMENSION2" VARCHAR2(200), 
	"DIMENSION3" VARCHAR2(200), 
	"GENERATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_REPORT_CACHE" PRIMARY KEY ("CACHE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 