
  CREATE TABLE "DIVINGAPP"."REPORT_ALERTS" 
   (	"ALERT_ID" NUMBER NOT NULL ENABLE, 
	"ALERT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"SEVERITY" VARCHAR2(10) NOT NULL ENABLE, 
	"METRIC_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CURRENT_VALUE" NUMBER(15,2), 
	"THRESHOLD_VALUE" NUMBER(15,2), 
	"DEVIATION" NUMBER(10,4), 
	"MESSAGE" VARCHAR2(500), 
	"DETECTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) DEFAULT 'NEW' NOT NULL ENABLE, 
	 CONSTRAINT "CK_RA_SEVERITY" CHECK (SEVERITY IN ('HIGH', 'MEDIUM', 'LOW')) ENABLE, 
	 CONSTRAINT "CK_RA_STATUS" CHECK (STATUS IN ('NEW', 'ACKNOWLEDGED', 'RESOLVED')) ENABLE, 
	 CONSTRAINT "PK_REPORT_ALERTS" PRIMARY KEY ("ALERT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 