
  CREATE TABLE "DIVINGAPP"."RESERVATIONS" 
   (	"RESERVATION_ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"SCHEDULE_ID" NUMBER NOT NULL ENABLE, 
	"NUM_PARTICIPANTS" NUMBER NOT NULL ENABLE, 
	"TOTAL_PRICE" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) DEFAULT 'CONFIRMED' NOT NULL ENABLE, 
	"CANCEL_REASON" VARCHAR2(500), 
	"REFUND_AMOUNT" NUMBER(10,0) DEFAULT 0, 
	"NOTES" VARCHAR2(1000), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CK_RES_STATUS" CHECK (STATUS IN ('CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')) ENABLE, 
	 CONSTRAINT "PK_RESERVATIONS" PRIMARY KEY ("RESERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_RES_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "DIVINGAPP"."CUSTOMERS" ("CUSTOMER_ID") ENABLE, 
	 CONSTRAINT "FK_RES_SCHEDULE" FOREIGN KEY ("SCHEDULE_ID")
	  REFERENCES "DIVINGAPP"."TOUR_SCHEDULES" ("SCHEDULE_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 