
  CREATE TABLE "DIVINGAPP"."RESERVATION_OPTIONS" 
   (	"RES_OPTION_ID" NUMBER NOT NULL ENABLE, 
	"RESERVATION_ID" NUMBER NOT NULL ENABLE, 
	"OPTION_ID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"SUBTOTAL" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_RESERVATION_OPTIONS" PRIMARY KEY ("RES_OPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_RO_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "DIVINGAPP"."RESERVATIONS" ("RESERVATION_ID") ENABLE, 
	 CONSTRAINT "FK_RO_OPTION" FOREIGN KEY ("OPTION_ID")
	  REFERENCES "DIVINGAPP"."OPTIONS_MASTER" ("OPTION_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 