
  CREATE TABLE "DIVINGAPP"."TOUR_DIVE_SITES" 
   (	"TOUR_ID" NUMBER NOT NULL ENABLE, 
	"SITE_ID" NUMBER NOT NULL ENABLE, 
	"DIVE_ORDER" NUMBER DEFAULT 1, 
	 CONSTRAINT "PK_TOUR_DIVE_SITES" PRIMARY KEY ("TOUR_ID", "SITE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_TDS_TOUR" FOREIGN KEY ("TOUR_ID")
	  REFERENCES "DIVINGAPP"."TOURS" ("TOUR_ID") ENABLE, 
	 CONSTRAINT "FK_TDS_SITE" FOREIGN KEY ("SITE_ID")
	  REFERENCES "DIVINGAPP"."DIVE_SITES" ("SITE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 