
  CREATE TABLE "DIVINGAPP"."TOUR_SCHEDULES" 
   (	"SCHEDULE_ID" NUMBER NOT NULL ENABLE, 
	"TOUR_ID" NUMBER NOT NULL ENABLE, 
	"TOUR_DATE" DATE NOT NULL ENABLE, 
	"START_TIME" VARCHAR2(5), 
	"REMAINING_SEATS" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) DEFAULT 'OPEN' NOT NULL ENABLE, 
	"VERSION" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CK_TS_STATUS" CHECK (STATUS IN ('OPEN', 'FULL', 'CLOSED', 'CANCELLED')) ENABLE, 
	 CONSTRAINT "PK_TOUR_SCHEDULES" PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_TS_TOUR" FOREIGN KEY ("TOUR_ID")
	  REFERENCES "DIVINGAPP"."TOURS" ("TOUR_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 