
  CREATE TABLE "DIVINGAPP"."TOUR_INSTRUCTORS" 
   (	"TOUR_ID" NUMBER NOT NULL ENABLE, 
	"INSTRUCTOR_ID" NUMBER NOT NULL ENABLE, 
	"ROLE" VARCHAR2(50) DEFAULT 'GUIDE', 
	 CONSTRAINT "PK_TOUR_INSTRUCTORS" PRIMARY KEY ("TOUR_ID", "INSTRUCTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_TI_TOUR" FOREIGN KEY ("TOUR_ID")
	  REFERENCES "DIVINGAPP"."TOURS" ("TOUR_ID") ENABLE, 
	 CONSTRAINT "FK_TI_INSTRUCTOR" FOREIGN KEY ("INSTRUCTOR_ID")
	  REFERENCES "DIVINGAPP"."INSTRUCTORS" ("INSTRUCTOR_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 