
  CREATE TABLE "DIVINGAPP"."TOURS" 
   (	"TOUR_ID" NUMBER NOT NULL ENABLE, 
	"TOUR_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"DESCRIPTION" CLOB, 
	"AREA" VARCHAR2(100) NOT NULL ENABLE, 
	"DIFFICULTY" VARCHAR2(20) NOT NULL ENABLE, 
	"MAX_PARTICIPANTS" NUMBER NOT NULL ENABLE, 
	"BASE_PRICE" NUMBER(10,0) NOT NULL ENABLE, 
	"DURATION_DAYS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"MIN_DIVE_COUNT" NUMBER DEFAULT 0, 
	"FEATURED_FLAG" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CK_TOURS_DIFFICULTY" CHECK (DIFFICULTY IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')) ENABLE, 
	 CONSTRAINT "CK_TOURS_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'DELETED')) ENABLE, 
	 CONSTRAINT "CK_TOURS_FEATURED" CHECK (FEATURED_FLAG IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "PK_TOURS" PRIMARY KEY ("TOUR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 