-- =============================================================
-- V001__create_tables.sql
-- ダイビングツアーアプリケーション テーブル定義DDL
-- Oracle 19c 向け
-- =============================================================

-- =====================
-- シーケンス
-- =====================
CREATE SEQUENCE SEQ_CUSTOMERS       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TOURS           START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TOUR_SCHEDULES  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DIVE_SITES      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INSTRUCTORS     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVATIONS    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OPTIONS_MASTER  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVATION_OPTIONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DIVING_LOGS     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NEWS            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ADMIN_USERS     START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================
-- 顧客テーブル
-- =====================
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID     NUMBER          NOT NULL,
    EMAIL           VARCHAR2(255)   NOT NULL,
    PASSWORD_HASH   RAW(64)         NOT NULL,
    LAST_NAME       VARCHAR2(100)   NOT NULL,
    FIRST_NAME      VARCHAR2(100)   NOT NULL,
    LAST_NAME_KANA  VARCHAR2(100),
    FIRST_NAME_KANA VARCHAR2(100),
    PHONE           VARCHAR2(20),
    BIRTH_DATE      DATE,
    LICENSE_LEVEL   VARCHAR2(50),
    DIVE_COUNT      NUMBER DEFAULT 0,
    EMERGENCY_CONTACT VARCHAR2(200),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CUSTOMERS_EMAIL UNIQUE (EMAIL)
);

-- =====================
-- ツアーテーブル
-- =====================
CREATE TABLE TOURS (
    TOUR_ID         NUMBER          NOT NULL,
    TOUR_NAME       VARCHAR2(200)   NOT NULL,
    DESCRIPTION     CLOB,
    AREA            VARCHAR2(100)   NOT NULL,
    DIFFICULTY      VARCHAR2(20)    NOT NULL,
    MAX_PARTICIPANTS NUMBER         NOT NULL,
    BASE_PRICE      NUMBER(10,0)   NOT NULL,
    DURATION_DAYS   NUMBER          DEFAULT 1 NOT NULL,
    MIN_DIVE_COUNT  NUMBER          DEFAULT 0,
    FEATURED_FLAG   CHAR(1)         DEFAULT 'N' NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TOURS PRIMARY KEY (TOUR_ID),
    CONSTRAINT CK_TOURS_DIFFICULTY CHECK (DIFFICULTY IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')),
    CONSTRAINT CK_TOURS_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    CONSTRAINT CK_TOURS_FEATURED CHECK (FEATURED_FLAG IN ('Y', 'N'))
);

-- =====================
-- ツアースケジュールテーブル
-- =====================
CREATE TABLE TOUR_SCHEDULES (
    SCHEDULE_ID     NUMBER          NOT NULL,
    TOUR_ID         NUMBER          NOT NULL,
    TOUR_DATE       DATE            NOT NULL,
    START_TIME      VARCHAR2(5),
    REMAINING_SEATS NUMBER          NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'OPEN' NOT NULL,
    VERSION         NUMBER          DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TOUR_SCHEDULES PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT FK_TS_TOUR FOREIGN KEY (TOUR_ID) REFERENCES TOURS(TOUR_ID),
    CONSTRAINT CK_TS_STATUS CHECK (STATUS IN ('OPEN', 'FULL', 'CLOSED', 'CANCELLED'))
);

-- =====================
-- ダイブサイトテーブル
-- =====================
CREATE TABLE DIVE_SITES (
    SITE_ID         NUMBER          NOT NULL,
    SITE_NAME       VARCHAR2(200)   NOT NULL,
    AREA            VARCHAR2(100)   NOT NULL,
    DESCRIPTION     CLOB,
    MAX_DEPTH       NUMBER(5,1),
    WATER_TEMPERATURE_MIN NUMBER(4,1),
    WATER_TEMPERATURE_MAX NUMBER(4,1),
    DIFFICULTY      VARCHAR2(20),
    MARINE_LIFE     VARCHAR2(1000),
    ACCESS_INFO     VARCHAR2(500),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DIVE_SITES PRIMARY KEY (SITE_ID),
    CONSTRAINT CK_DS_DIFFICULTY CHECK (DIFFICULTY IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT'))
);

-- =====================
-- ツアー - ダイブサイト 紐付け（多対多）
-- =====================
CREATE TABLE TOUR_DIVE_SITES (
    TOUR_ID         NUMBER          NOT NULL,
    SITE_ID         NUMBER          NOT NULL,
    DIVE_ORDER      NUMBER          DEFAULT 1,
    CONSTRAINT PK_TOUR_DIVE_SITES PRIMARY KEY (TOUR_ID, SITE_ID),
    CONSTRAINT FK_TDS_TOUR FOREIGN KEY (TOUR_ID) REFERENCES TOURS(TOUR_ID),
    CONSTRAINT FK_TDS_SITE FOREIGN KEY (SITE_ID) REFERENCES DIVE_SITES(SITE_ID)
);

-- =====================
-- インストラクターテーブル
-- =====================
CREATE TABLE INSTRUCTORS (
    INSTRUCTOR_ID   NUMBER          NOT NULL,
    LAST_NAME       VARCHAR2(100)   NOT NULL,
    FIRST_NAME      VARCHAR2(100)   NOT NULL,
    CERTIFICATION   VARCHAR2(200),
    EXPERIENCE_YEARS NUMBER,
    SPECIALTY       VARCHAR2(200),
    PROFILE         CLOB,
    PHOTO_URL       VARCHAR2(500),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INSTRUCTORS PRIMARY KEY (INSTRUCTOR_ID)
);

-- =====================
-- ツアー - インストラクター 紐付け
-- =====================
CREATE TABLE TOUR_INSTRUCTORS (
    TOUR_ID         NUMBER          NOT NULL,
    INSTRUCTOR_ID   NUMBER          NOT NULL,
    ROLE            VARCHAR2(50)    DEFAULT 'GUIDE',
    CONSTRAINT PK_TOUR_INSTRUCTORS PRIMARY KEY (TOUR_ID, INSTRUCTOR_ID),
    CONSTRAINT FK_TI_TOUR FOREIGN KEY (TOUR_ID) REFERENCES TOURS(TOUR_ID),
    CONSTRAINT FK_TI_INSTRUCTOR FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORS(INSTRUCTOR_ID)
);

-- =====================
-- オプションマスタ
-- =====================
CREATE TABLE OPTIONS_MASTER (
    OPTION_ID       NUMBER          NOT NULL,
    OPTION_NAME     VARCHAR2(200)   NOT NULL,
    OPTION_CATEGORY VARCHAR2(50)    NOT NULL,
    UNIT_PRICE      NUMBER(10,0)   NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_OPTIONS_MASTER PRIMARY KEY (OPTION_ID),
    CONSTRAINT CK_OM_CATEGORY CHECK (OPTION_CATEGORY IN ('RENTAL', 'TRANSPORT', 'PHOTO', 'INSURANCE', 'OTHER'))
);

-- =====================
-- 予約テーブル
-- =====================
CREATE TABLE RESERVATIONS (
    RESERVATION_ID  NUMBER          NOT NULL,
    CUSTOMER_ID     NUMBER          NOT NULL,
    SCHEDULE_ID     NUMBER          NOT NULL,
    NUM_PARTICIPANTS NUMBER         NOT NULL,
    TOTAL_PRICE     NUMBER(10,0)   NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'CONFIRMED' NOT NULL,
    CANCEL_REASON   VARCHAR2(500),
    REFUND_AMOUNT   NUMBER(10,0)   DEFAULT 0,
    NOTES           VARCHAR2(1000),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RESERVATIONS PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT FK_RES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_RES_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES TOUR_SCHEDULES(SCHEDULE_ID),
    CONSTRAINT CK_RES_STATUS CHECK (STATUS IN ('CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW'))
);

-- =====================
-- 予約オプション
-- =====================
CREATE TABLE RESERVATION_OPTIONS (
    RES_OPTION_ID   NUMBER          NOT NULL,
    RESERVATION_ID  NUMBER          NOT NULL,
    OPTION_ID       NUMBER          NOT NULL,
    QUANTITY        NUMBER          DEFAULT 1 NOT NULL,
    SUBTOTAL        NUMBER(10,0)   NOT NULL,
    CONSTRAINT PK_RESERVATION_OPTIONS PRIMARY KEY (RES_OPTION_ID),
    CONSTRAINT FK_RO_RESERVATION FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(RESERVATION_ID),
    CONSTRAINT FK_RO_OPTION FOREIGN KEY (OPTION_ID) REFERENCES OPTIONS_MASTER(OPTION_ID)
);

-- =====================
-- ダイビングログ
-- =====================
CREATE TABLE DIVING_LOGS (
    LOG_ID          NUMBER          NOT NULL,
    CUSTOMER_ID     NUMBER          NOT NULL,
    SITE_ID         NUMBER,
    RESERVATION_ID  NUMBER,
    DIVE_DATE       DATE            NOT NULL,
    MAX_DEPTH       NUMBER(5,1),
    DIVE_TIME       NUMBER,
    WATER_TEMP      NUMBER(4,1),
    VISIBILITY      NUMBER(4,1),
    WEATHER         VARCHAR2(50),
    BUDDY           VARCHAR2(100),
    NOTES           CLOB,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DIVING_LOGS PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_DL_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_DL_SITE FOREIGN KEY (SITE_ID) REFERENCES DIVE_SITES(SITE_ID),
    CONSTRAINT FK_DL_RESERVATION FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(RESERVATION_ID)
);

-- =====================
-- ニュース（お知らせ）
-- =====================
CREATE TABLE NEWS (
    NEWS_ID         NUMBER          NOT NULL,
    TITLE           VARCHAR2(300)   NOT NULL,
    CONTENT         CLOB            NOT NULL,
    CATEGORY        VARCHAR2(50),
    PUBLISH_DATE    DATE            NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'PUBLISHED' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NEWS PRIMARY KEY (NEWS_ID),
    CONSTRAINT CK_NEWS_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

-- =====================
-- 管理者ユーザー
-- =====================
CREATE TABLE ADMIN_USERS (
    ADMIN_ID        NUMBER          NOT NULL,
    USERNAME        VARCHAR2(100)   NOT NULL,
    PASSWORD_HASH   RAW(64)         NOT NULL,
    DISPLAY_NAME    VARCHAR2(100)   NOT NULL,
    ROLE            VARCHAR2(50)    DEFAULT 'ADMIN' NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    LAST_LOGIN_AT   TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_USERS PRIMARY KEY (ADMIN_ID),
    CONSTRAINT UK_ADMIN_USERS_USERNAME UNIQUE (USERNAME)
);

-- =====================
-- インデックス
-- =====================
CREATE INDEX IDX_CUSTOMERS_STATUS ON CUSTOMERS(STATUS);
CREATE INDEX IDX_TOURS_AREA ON TOURS(AREA);
CREATE INDEX IDX_TOURS_DIFFICULTY ON TOURS(DIFFICULTY);
CREATE INDEX IDX_TOURS_STATUS ON TOURS(STATUS);
CREATE INDEX IDX_TOURS_FEATURED ON TOURS(FEATURED_FLAG);
CREATE INDEX IDX_TS_TOUR_DATE ON TOUR_SCHEDULES(TOUR_DATE);
CREATE INDEX IDX_TS_TOUR_ID ON TOUR_SCHEDULES(TOUR_ID);
CREATE INDEX IDX_TS_STATUS ON TOUR_SCHEDULES(STATUS);
CREATE INDEX IDX_DS_AREA ON DIVE_SITES(AREA);
CREATE INDEX IDX_RESERVATIONS_CUSTOMER ON RESERVATIONS(CUSTOMER_ID);
CREATE INDEX IDX_RESERVATIONS_SCHEDULE ON RESERVATIONS(SCHEDULE_ID);
CREATE INDEX IDX_RESERVATIONS_STATUS ON RESERVATIONS(STATUS);
CREATE INDEX IDX_RO_RESERVATION ON RESERVATION_OPTIONS(RESERVATION_ID);
CREATE INDEX IDX_DL_CUSTOMER ON DIVING_LOGS(CUSTOMER_ID);
CREATE INDEX IDX_DL_DIVE_DATE ON DIVING_LOGS(DIVE_DATE);
CREATE INDEX IDX_NEWS_PUBLISH ON NEWS(PUBLISH_DATE, STATUS);
