-- =============================================================
-- V003__insert_master_data.sql
-- マスタデータ・初期データ投入
-- =============================================================

-- =====================
-- オプションマスタ
-- =====================
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, 'フルレンタル器材セット', 'RENTAL', 8000, 'BCD、レギュレーター、ウェットスーツ、マスク、フィン一式');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, '重器材レンタル', 'RENTAL', 5000, 'BCD、レギュレーターセット');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, '軽器材レンタル', 'RENTAL', 3000, 'マスク、フィン、スノーケル、ブーツ');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, '水中カメラレンタル', 'RENTAL', 3500, '水中デジタルカメラ（SDカード付き）');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, '送迎サービス（片道）', 'TRANSPORT', 2000, '最寄り駅/空港からショップまでの送迎');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, '送迎サービス（往復）', 'TRANSPORT', 3500, '最寄り駅/空港からショップまでの往復送迎');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, '水中写真撮影サービス', 'PHOTO', 5000, 'プロカメラマンによる水中撮影（データお渡し）');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, 'ダイビング保険（1日）', 'INSURANCE', 1500, 'DAN Japan ダイビング傷害保険 1日プラン');
INSERT INTO OPTIONS_MASTER (OPTION_ID, OPTION_NAME, OPTION_CATEGORY, UNIT_PRICE, DESCRIPTION)
VALUES (SEQ_OPTIONS_MASTER.NEXTVAL, 'ナイトロックス（1本）', 'OTHER', 1000, 'エンリッチドエア ナイトロックス（EANx32）');

-- =====================
-- 管理者ユーザー（初期パスワード: admin123）
-- SHA-256ハッシュ
-- =====================
INSERT INTO ADMIN_USERS (ADMIN_ID, USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE)
VALUES (SEQ_ADMIN_USERS.NEXTVAL, 'admin',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('admin123', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        'システム管理者', 'ADMIN');

COMMIT;
