-- =============================================================
-- 01_create_user.sql
-- アプリケーション用スキーマユーザー DIVINGAPP の作成
-- Oracle 19c XE (PDB: XEPDB1) 向け
-- =============================================================

ALTER SESSION SET CONTAINER = XEPDB1;

-- ユーザー作成
CREATE USER DIVINGAPP IDENTIFIED BY divingapp123
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

-- 基本権限
GRANT CONNECT TO DIVINGAPP;
GRANT RESOURCE TO DIVINGAPP;
GRANT CREATE VIEW TO DIVINGAPP;
GRANT CREATE SEQUENCE TO DIVINGAPP;
GRANT CREATE PROCEDURE TO DIVINGAPP;
GRANT CREATE TRIGGER TO DIVINGAPP;

-- DBMS_CRYPTO パッケージの実行権限（パスワードハッシュ用）
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO DIVINGAPP;

-- DBMS_OUTPUT（デバッグ用）
GRANT EXECUTE ON SYS.DBMS_OUTPUT TO DIVINGAPP;

EXIT;
