-- =============================================================
-- sample_data.sql
-- 開発用サンプルデータ
-- =============================================================

-- =====================
-- ダイブサイト
-- =====================
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '青の洞窟', '沖縄・恩納村', '神秘的な青い光が差し込む人気No.1のダイブスポット。洞窟内にはリュウキュウハタンポの群れが見られます。', 8.0, 22.0, 29.0, 'BEGINNER', 'リュウキュウハタンポ、クマノミ、ツバメウオ、ハリセンボン', 'ボートで約5分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '慶良間諸島 座間味', '沖縄・慶良間', '世界屈指の透明度を誇るケラマブルーの海。ウミガメとの遭遇率は非常に高い。', 30.0, 21.0, 29.0, 'INTERMEDIATE', 'ウミガメ、マンタ、カクレクマノミ、デバスズメダイの群れ', '那覇から高速船で約50分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '石垣島 マンタスクランブル', '沖縄・石垣島', '世界有数のマンタ遭遇ポイント。秋のシーズンには複数のマンタが乱舞する圧巻の光景。', 15.0, 23.0, 30.0, 'INTERMEDIATE', 'マンタ、ナンヨウマンタ、カスミチョウチョウウオ、グルクン', 'ボートで約30分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '与那国島 海底遺跡', '沖縄・与那国', '謎の海底遺跡として世界的に有名なポイント。巨大な階段状の地形は圧巻。冬季にはハンマーヘッドシャークも。', 25.0, 22.0, 28.0, 'ADVANCED', 'ハンマーヘッドシャーク、バラクーダ、ロウニンアジ、イソマグロ', 'ボートで約15分、ドリフトダイブ');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '伊豆・大瀬崎', '静岡・伊豆', '東京から日帰り可能な人気スポット。マンボウが見られることも。豊富なマクロ生物が魅力。', 20.0, 14.0, 26.0, 'BEGINNER', 'マンボウ、ミノカサゴ、ウミウシ各種、タツノオトシゴ', '東京から車で約2時間半');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '屋久島・一湊', '鹿児島・屋久島', '世界自然遺産の島のダイビングスポット。ウミガメの大群が見られる。', 25.0, 19.0, 28.0, 'INTERMEDIATE', 'ウミガメ、ゼブラハゼ、ニシキフウライウオ、カンパチの群れ', '宮之浦港から車で約20分');

-- =====================
-- インストラクター
-- =====================
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '海野', '太郎', 'PADI マスターインストラクター / EFR インストラクター', 15, 'ファンダイビング、水中写真',
        '沖縄の海に魅了されて移住して15年。年間300本以上のダイブで沖縄の海を知り尽くしています。初心者から上級者まで、お客様のレベルに合わせた楽しいダイビングをご提供します。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '珊瑚', '美咲', 'PADI IDCスタッフインストラクター / TecRec インストラクター', 10, 'テクニカルダイビング、洞窟ダイビング',
        'テクニカルダイビングのスペシャリスト。与那国の海底遺跡や洞窟ダイビングのガイド経験が豊富です。安全第一で、未知の水中世界へご案内します。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '波多', '健一', 'PADI オープンウォーターインストラクター / DAN 酸素プロバイダー', 8, '体験ダイビング、ライセンス講習',
        '元プロサーファーの経歴を持つインストラクター。初めての方に寄り添った丁寧な指導が好評です。体験ダイビングならお任せください。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '深海', 'ゆき', 'PADI マスターインストラクター / 水中写真家', 12, 'フォトダイビング、マクロ撮影',
        '水中写真コンテスト入賞多数。マクロ撮影のテクニックを活かしたフォトダイブツアーが人気です。ウミウシからマンタまで、最高の一枚を一緒に撮りましょう。');

-- =====================
-- ツアー
-- =====================
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '青の洞窟 体験ダイビング', '沖縄・恩納村の人気スポット「青の洞窟」で体験ダイビング！初めての方でも安心のマンツーマンサポート。神秘的な青い光の世界をお楽しみください。', '沖縄・恩納村', 'BEGINNER', 8, 12000, 1, 0, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '慶良間諸島 ウミガメと泳ぐ2ダイブ', 'ケラマブルーの透明な海で、ウミガメと一緒に泳ぐ感動体験。1日2ダイブのファンダイビングツアーです。高確率でウミガメに会えます！', '沖縄・慶良間', 'INTERMEDIATE', 6, 22000, 1, 10, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '石垣島マンタツアー 3日間', '石垣島のマンタスクランブルで大迫力のマンタウォッチング。3日間で計6ダイブ、マンタ遭遇率90%以上のプレミアムツアー。宿泊付き。', '沖縄・石垣島', 'INTERMEDIATE', 6, 85000, 3, 20, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '与那国 海底遺跡＆ハンマーヘッド', '謎の海底遺跡探検とハンマーヘッドシャークを狙う上級者向けエキサイティングツアー。ドリフトダイブ経験必須。2日間で4ダイブ。', '沖縄・与那国', 'ADVANCED', 4, 68000, 2, 50, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '伊豆・大瀬崎 日帰りダイブ', '東京から日帰りOK！伊豆の人気ポイント大瀬崎で2ダイブ。季節ごとに変わる海の生物を楽しめます。ランチ付き。', '静岡・伊豆', 'BEGINNER', 8, 18000, 1, 0, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '屋久島 ウミガメ天国ツアー 2日間', '世界遺産・屋久島の海でウミガメの大群と泳ぐ。陸では縄文杉トレッキングも楽しめるスペシャルプラン。', '鹿児島・屋久島', 'INTERMEDIATE', 6, 55000, 2, 10, 'Y');

-- =====================
-- ツアー - ダイブサイト紐付け
-- =====================
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (1, 1, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (2, 2, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (3, 3, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (4, 4, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (5, 5, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (6, 6, 1);

-- =====================
-- ツアー - インストラクター紐付け
-- =====================
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (1, 3, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (2, 1, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (3, 1, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (3, 4, 'PHOTOGRAPHER');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (4, 2, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (5, 3, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (6, 1, 'GUIDE');

-- =====================
-- ツアースケジュール（今後の日程）
-- =====================
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-04-15', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-04-20', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-05-03', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 2, DATE '2026-04-18', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 2, DATE '2026-05-10', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 3, DATE '2026-05-01', '07:30', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 3, DATE '2026-06-15', '07:30', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 4, DATE '2026-05-20', '07:00', 4, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 5, DATE '2026-04-12', '07:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 5, DATE '2026-04-26', '07:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 6, DATE '2026-05-15', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS)
VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 6, DATE '2026-06-20', '08:00', 6, 'OPEN');

-- =====================
-- ニュース
-- =====================
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '2026年ゴールデンウィーク特別ツアー受付開始！',
        '今年のGWは沖縄でダイビング！青の洞窟体験ダイビングと慶良間ファンダイブの特別プランをご用意しました。早期予約で10%OFF。',
        'CAMPAIGN', DATE '2026-03-15');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '石垣島マンタツアー 2026シーズン開始',
        '今年もマンタシーズンがやってきました！5月から10月まで、マンタスクランブルで大迫力のマンタウォッチングをお楽しみください。',
        'TOUR', DATE '2026-03-20');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '新インストラクター着任のお知らせ',
        '4月より水中写真家の深海ゆきインストラクターが着任しました。フォトダイビングツアーも新たに開催予定です。',
        'INFO', DATE '2026-03-25');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, 'サイトリニューアルのお知らせ',
        'ウェブサイトをリニューアルしました。ツアーの検索・予約がより便利になりました。ぜひご利用ください。',
        'INFO', DATE '2026-03-28');

-- =====================
-- テスト用顧客（パスワード: test1234）
-- =====================
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'tanaka@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '田中', '太郎', 'タナカ', 'タロウ', '090-1234-5678', DATE '1990-05-15', 'PADI アドバンスド・オープンウォーター', 35);
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'suzuki@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '鈴木', '花子', 'スズキ', 'ハナコ', '080-9876-5432', DATE '1995-08-20', 'PADI オープンウォーター', 8);

COMMIT;
