-- =============================================================
-- sample_data.sql
-- 開発用サンプルデータ
-- =============================================================

-- =====================
-- ダイブサイト（30か所）
-- =====================

-- 沖縄エリア（12か所）
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '青の洞窟', '沖縄・恩納村', '神秘的な青い光が差し込む人気No.1のダイブスポット。洞窟内にはリュウキュウハタンポの群れが見られます。', 8.0, 22.0, 29.0, 'BEGINNER', 'リュウキュウハタンポ、クマノミ、ツバメウオ、ハリセンボン', 'ボートで約5分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '慶良間諸島 座間味', '沖縄・慶良間', '世界屈指の透明度を誇るケラマブルーの海。ウミガメとの遭遇率は非常に高い。', 30.0, 21.0, 29.0, 'INTERMEDIATE', 'ウミガメ、マンタ、カクレクマノミ、デバスズメダイの群れ', '那覇から高速船で約50分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '石垣島 マンタスクランブル', '沖縄・石垣島', '世界有数のマンタ遭遇ポイント。秋のシーズンには複数のマンタが乱舞する圧巻の光景。', 15.0, 23.0, 30.0, 'INTERMEDIATE', 'マンタ、ナンヨウマンタ、カスミチョウチョウウオ、グルクン', 'ボートで約30分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '与那国島 海底遺跡', '沖縄・与那国', '謎の海底遺跡として世界的に有名なポイント。巨大な階段状の地形は圧巻。冬季にはハンマーヘッドシャークも。', 25.0, 22.0, 28.0, 'ADVANCED', 'ハンマーヘッドシャーク、バラクーダ、ロウニンアジ、イソマグロ', 'ボートで約15分、ドリフトダイブ');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '万座ドリームホール', '沖縄・恩納村', '垂直に降りる縦穴から光のカーテンが差し込む幻想的なケーブダイブポイント。', 30.0, 22.0, 29.0, 'ADVANCED', 'アカマツカサ、ハタンポ、ウコンハネガイ、リュウキュウハタンポ', 'ボートで約10分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, 'ゴリラチョップ', '沖縄・本部', '初心者でも気軽にエントリーできるビーチダイブポイント。多彩なサンゴと熱帯魚のパラダイス。', 10.0, 21.0, 29.0, 'BEGINNER', 'クマノミ各種、チョウチョウウオ、デバスズメダイ、ルリスズメダイ', 'ビーチエントリー、駐車場あり');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '砂辺 No.1', '沖縄・北谷', '沖縄中部の人気ナイトダイブスポット。ソフトコーラルの群生地としても有名。', 18.0, 21.0, 28.0, 'BEGINNER', 'ソフトコーラル群生、ウミウシ各種、コブシメ、タコ', 'ビーチエントリー、器材洗い場あり');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '渡嘉敷島 アリガーケーブル', '沖縄・慶良間', 'ケラマ諸島を代表するポイント。ドロップオフの壁沿いのダイブはスリル満点。', 35.0, 21.0, 29.0, 'INTERMEDIATE', 'ウミガメ、ナポレオンフィッシュ、カスミアジ群れ、イソバナ', '渡嘉敷港からボートで約10分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '宮古島 通り池', '沖縄・宮古島', '国の天然記念物にも指定された神秘的な地形ポイント。淡水と海水が混じる境界層（ハロクライン）が幻想的。', 40.0, 22.0, 29.0, 'ADVANCED', 'アカマツカサ、リュウキュウハタンポ、ロウニンアジ、テングハギモドキ', 'ボートで約20分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '宮古島 魔王の宮殿', '沖縄・宮古島', '宮古島を代表する地形ポイント。洞窟内に差し込む光のシャワーが「魔王の宮殿」の名にふさわしい。', 25.0, 22.0, 29.0, 'INTERMEDIATE', 'リュウキュウハタンポ、アカマツカサ、オトヒメエビ、ウコンハネガイ', 'ボートで約15分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '石垣島 米原Wリーフ', '沖縄・石垣島', '二重のリーフが広がる石垣島北部のカラフルなポイント。枝サンゴの群落が圧巻。', 12.0, 23.0, 30.0, 'BEGINNER', 'デバスズメダイ大群、ハマクマノミ、チョウチョウウオ各種、シャコガイ', 'ボートで約15分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '久米島 はての浜沖', '沖縄・久米島', '東洋一と称される白砂の島「はての浜」沖のポイント。真っ白な砂地にガーデンイールの群生が見られる。', 20.0, 22.0, 28.0, 'BEGINNER', 'ガーデンイール、マンタ、ウミガメ、ジョーフィッシュ', 'ボートで約25分');

-- 伊豆エリア（6か所）
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '大瀬崎 柵下', '静岡・伊豆', '東京から日帰り可能な人気スポット。マンボウが見られることも。豊富なマクロ生物が魅力。', 20.0, 14.0, 26.0, 'BEGINNER', 'マンボウ、ミノカサゴ、ウミウシ各種、タツノオトシゴ', '東京から車で約2時間半');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '大瀬崎 外海', '静岡・伊豆', '沖合に面したダイナミックなドロップオフ。ソフトコーラルの群生とワイド撮影に最適。', 30.0, 14.0, 25.0, 'INTERMEDIATE', 'キンギョハナダイ群れ、サクラダイ、ソフトコーラル、ミノカサゴ', '大瀬崎マリンパークから徒歩');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '雲見', '静岡・伊豆', '洞窟・アーチ・トンネルが連なるダイナミックな地形ポイント。光のカーテンが美しい。', 25.0, 14.0, 26.0, 'INTERMEDIATE', 'テングダイ、クエ、カンパチ群れ、ウツボ各種', '東名高速沼津ICから車で約1.5時間');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '伊豆海洋公園', '静岡・伊豆', '施設が充実した初心者にも安心のダイブスポット。春先のウミウシ天国は必見。', 18.0, 13.0, 26.0, 'BEGINNER', 'ウミウシ各種、カエルアンコウ、ダンゴウオ、クマノミ', 'JR伊豆高原駅から送迎あり');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '初島', '静岡・伊豆', '熱海から船で30分の離島ダイブ。黒潮の恩恵で魚影が濃い。秋にはカメ・エイも出現。', 22.0, 15.0, 27.0, 'INTERMEDIATE', 'ブリ群れ、アオウミガメ、トビエイ、キンギョハナダイ', '熱海港から高速船で約30分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '堂ヶ島', '静岡・伊豆', '天窓洞や三四郎島など奇岩が織りなす西伊豆の景勝地。洞窟内の光と色彩が魅力。', 20.0, 14.0, 25.0, 'INTERMEDIATE', 'テングダイ、イセエビ、ウツボ、ネコザメ', '修善寺から車で約50分');

-- 屋久島・鹿児島エリア（4か所）
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '屋久島 一湊', '鹿児島・屋久島', '世界自然遺産の島のダイビングスポット。ウミガメの大群が見られる。', 25.0, 19.0, 28.0, 'INTERMEDIATE', 'ウミガメ、ゼブラハゼ、ニシキフウライウオ、カンパチの群れ', '宮之浦港から車で約20分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '屋久島 お宮前', '鹿児島・屋久島', '屋久島を代表するウミガメポイント。高確率でアオウミガメと泳げる穏やかなポイント。', 15.0, 19.0, 28.0, 'BEGINNER', 'アオウミガメ、タイマイ、クマノミ各種、チョウチョウウオ', '宮之浦港から車で約15分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '奄美大島 倉崎海岸', '鹿児島・奄美大島', '手つかずの自然が残る奄美のビーチポイント。色とりどりのサンゴとウミガメに出会える。', 18.0, 20.0, 29.0, 'BEGINNER', 'ウミガメ、クマノミ各種、チンアナゴ、ヤッコ各種', 'ビーチエントリー、駐車場完備');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '奄美大島 山本スペシャル', '鹿児島・奄美大島', '大物・回遊魚の通り道。流れに乗ったドリフトダイブでカンパチやバラクーダの群れを狙う。', 35.0, 20.0, 28.0, 'ADVANCED', 'バラクーダ群れ、カンパチ群れ、ロウニンアジ、イソマグロ', 'ボートで約20分、ドリフトダイブ');

-- 和歌山エリア（4か所）
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '串本 グラスワールド', '和歌山・串本', '本州最南端の町・串本を代表するポイント。黒潮の恩恵でサンゴと熱帯魚が豊富。', 18.0, 17.0, 28.0, 'BEGINNER', 'テーブルサンゴ群生、カゴカキダイ群れ、ピグミーシーホース、アオウミガメ', 'ボートで約5分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '串本 住崎', '和歌山・串本', '串本エリアで最も有名なポイント。アーチやオーバーハングなど変化に富んだ地形。', 25.0, 17.0, 28.0, 'INTERMEDIATE', 'イサキ大群、カンパチ、アオリイカ産卵、ミナミハコフグ幼魚', 'ボートで約8分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '白浜 沈船', '和歌山・白浜', '水深18mに沈む漁船の残骸が人工漁礁となり多彩な魚が集まる。フィッシュウォッチングに最適。', 20.0, 16.0, 27.0, 'INTERMEDIATE', 'キンメモドキ大群、オオモンカエルアンコウ、ミノカサゴ、タツノオトシゴ', 'ボートで約10分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '白浜 沖の島', '和歌山・白浜', '白浜沖の離れ根ポイント。潮通しが良く、回遊魚やウミガメの遭遇率が高い。', 28.0, 16.0, 27.0, 'ADVANCED', 'カンパチ群れ、ブリ、ウミガメ、イサキ大群、ツバス', 'ボートで約15分、ドリフトあり');

-- 小笠原・高知エリア（4か所）
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '小笠原 閂ロック', '東京・小笠原', '世界自然遺産・小笠原を代表するポイント。イルカやシロワニ（シロザメ）との遭遇も。', 30.0, 21.0, 28.0, 'ADVANCED', 'シロワニ、イルカ、マグロ群れ、ナポレオンフィッシュ', '父島からボートで約40分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '小笠原 マグロ穴', '東京・小笠原', 'その名の通りイソマグロが群れるポイント。洞窟の中でマグロの群れに囲まれる贅沢な体験。', 25.0, 21.0, 28.0, 'INTERMEDIATE', 'イソマグロ大群、ユウゼン、テングダイ、アカヒメジ群れ', '父島からボートで約30分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '柏島 後浜', '高知・柏島', '日本屈指の透明度を誇る高知・柏島。マクロ生物の宝庫で水中写真家に大人気。', 20.0, 17.0, 27.0, 'BEGINNER', 'カエルアンコウ各種、ハナヒゲウツボ、ピグミーシーホース、ウミウシ各種', 'ボートで約5分');
INSERT INTO DIVE_SITES (SITE_ID, SITE_NAME, AREA, DESCRIPTION, MAX_DEPTH, WATER_TEMPERATURE_MIN, WATER_TEMPERATURE_MAX, DIFFICULTY, MARINE_LIFE, ACCESS_INFO)
VALUES (SEQ_DIVE_SITES.NEXTVAL, '柏島 竜の浜', '高知・柏島', '砂地とサンゴが混在する柏島の人気ポイント。レアな甲殻類やハゼ類の天国。', 18.0, 17.0, 27.0, 'INTERMEDIATE', 'オシャレハナダイ、ジョーフィッシュ、フリソデエビ、ニシキフウライウオ', 'ボートで約8分');

-- =====================
-- インストラクター（10名）
-- =====================
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '海野', '太郎', 'PADI マスターインストラクター / EFR インストラクター', 15, 'ファンダイビング、水中写真',
        '沖縄の海に魅了されて移住して15年。年間300本以上のダイブで沖縄の海を知り尽くしています。初心者から上級者まで、お客様のレベルに合わせた楽しいダイビングをご提供します。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '珊瑚', '美咲', 'PADI IDCスタッフインストラクター / TecRec インストラクター', 10, 'テクニカルダイビング、洞窟ダイビング',
        'テクニカルダイビングのスペシャリスト。与那国の海底遺跡や洞窟ダイビングのガイド経験が豊富です。安全第一で、未知の水中世界へご案内します。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '波多', '健一', 'PADI オープンウォーターインストラクター / DAN 酸素プロバイダー', 8, '体験ダイビング、ライセンス講習',
        '元プロサーファーの経歴を持つインストラクター。初めての方に寄り添った丁寧な指導が好評です。体験ダイビングならお任せください。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '深海', 'ゆき', 'PADI マスターインストラクター / 水中写真家', 12, 'フォトダイビング、マクロ撮影',
        '水中写真コンテスト入賞多数。マクロ撮影のテクニックを活かしたフォトダイブツアーが人気です。ウミウシからマンタまで、最高の一枚を一緒に撮りましょう。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '島袋', '翔', 'NAUI インストラクター / レスキューダイバートレーナー', 7, 'レスキュートレーニング、ボートダイブ',
        '元海上保安庁のダイバー。安全管理のプロフェッショナルとして、どんな状況でも冷静に対応します。レスキューダイバー講習も担当。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '黒潮', 'あかり', 'PADI マスタースクーバダイバートレーナー / SSI インストラクター', 9, 'ナイトダイビング、ドリフトダイブ',
        '宮古島在住のベテランガイド。宮古島の地形ポイントを知り尽くした洞窟・地形ダイブのスペシャリスト。夜の海の魅力もお伝えします。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '磯辺', '大地', 'PADI オープンウォーターインストラクター / EFR インストラクター', 5, '体験ダイビング、スノーケリング',
        '伊豆を拠点に活動する若手インストラクター。学生時代から潜り続けて1000本超。明るいキャラクターで初めてのお客様にも大人気。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '南風', 'まりな', 'PADI IDCスタッフインストラクター / DSAT テックディープ', 11, 'ディープダイビング、サイドマウント',
        '石垣島でマンタガイドを10年以上担当。マンタの個体識別ができるほどの観察眼で、最高のマンタ体験をお約束します。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '渡辺', '隼人', 'NAUI マスタースクーバダイバー / DAN 酸素プロバイダー', 6, 'ファンダイビング、フィッシュウォッチング',
        '魚類学を専攻した海洋生物のエキスパート。ダイビング中のフィッシュブリーフィングは他では聞けない専門知識満載。図鑑にない裏話も。');
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, LAST_NAME, FIRST_NAME, CERTIFICATION, EXPERIENCE_YEARS, SPECIALTY, PROFILE)
VALUES (SEQ_INSTRUCTORS.NEXTVAL, '天城', 'さくら', 'PADI オープンウォーターインストラクター / ドライスーツSP', 4, '講習、ナイトダイビング',
        '和歌山・串本をホームグランドに活動。サンゴの生態調査にも参加する環境保全派ダイバー。海への愛情あふれるガイドが好評です。');

-- =====================
-- ツアー（20件）
-- =====================
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '青の洞窟 体験ダイビング', '沖縄・恩納村の人気スポット「青の洞窟」で体験ダイビング！初めての方でも安心のマンツーマンサポート。神秘的な青い光の世界をお楽しみください。', '沖縄・恩納村', 'BEGINNER', 8, 12000, 1, 0, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '慶良間諸島 ウミガメと泳ぐ2ダイブ', 'ケラマブルーの透明な海で、ウミガメと一緒に泳ぐ感動体験。1日2ダイブのファンダイビングツアーです。高確率でウミガメに会えます！', '沖縄・慶良間', 'INTERMEDIATE', 6, 22000, 1, 10, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '石垣島マンタツアー 3日間', '石垣島のマンタスクランブルで大迫力のマンタウォッチング。3日間で計6ダイブ、マンタ遭遇率90%以上のプレミアムツアー。宿泊付き。', '沖縄・石垣島', 'INTERMEDIATE', 6, 85000, 3, 20, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '与那国 海底遺跡＆ハンマーヘッド', '謎の海底遺跡探検とハンマーヘッドシャークを狙う上級者向けエキサイティングツアー。ドリフトダイブ経験必須。2日間で4ダイブ。', '沖縄・与那国', 'ADVANCED', 4, 68000, 2, 50, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '伊豆・大瀬崎 日帰りダイブ', '東京から日帰りOK！伊豆の人気ポイント大瀬崎で2ダイブ。季節ごとに変わる海の生物を楽しめます。ランチ付き。', '静岡・伊豆', 'BEGINNER', 8, 18000, 1, 0, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '屋久島 ウミガメ天国ツアー 2日間', '世界遺産・屋久島の海でウミガメの大群と泳ぐ。陸では縄文杉トレッキングも楽しめるスペシャルプラン。', '鹿児島・屋久島', 'INTERMEDIATE', 6, 55000, 2, 10, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '万座 ドリームホール冒険ダイブ', '恩納村の人気洞窟ポイント「ドリームホール」を探検。垂直に降りる縦穴から差し込む光のカーテンは感動もの。中級者以上限定。', '沖縄・恩納村', 'ADVANCED', 4, 18000, 1, 30, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, 'ゴリラチョップ＆瀬底島 体験ダイビング', '穏やかなビーチから入る体験ダイビング。カラフルなサンゴと熱帯魚の世界。午後は瀬底島でスノーケリングも楽しめます。', '沖縄・本部', 'BEGINNER', 10, 9800, 1, 0, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '宮古島 地形ダイブ三昧 3日間', '通り池、魔王の宮殿、アントニオ・ガウディなど宮古島の有名地形ポイントを3日間で制覇。宿泊・食事付きパッケージ。', '沖縄・宮古島', 'INTERMEDIATE', 6, 92000, 3, 20, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '久米島 はての浜＆ダイビング 2日間', '東洋一のビーチ「はての浜」上陸とダイビングがセットになった贅沢ツアー。ガーデンイールの群生やマンタも狙えます。', '沖縄・久米島', 'BEGINNER', 8, 48000, 2, 0, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '西伊豆・雲見 洞窟ダイブ日帰り', '伊豆最大級の洞窟ポイント・雲見で2ダイブ。アーチやトンネルを潜り抜ける冒険感満載のツアー。東京日帰り可能。', '静岡・伊豆', 'INTERMEDIATE', 6, 22000, 1, 10, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '伊豆海洋公園 ウミウシ＆マクロフォトダイブ', '春限定！ウミウシ天国の伊豆海洋公園でマクロフォトダイブ。水中写真家インストラクターが撮影テクニックもレクチャー。', '静岡・伊豆', 'BEGINNER', 8, 16000, 1, 0, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '奄美大島 サンゴ礁ダイビング 2日間', '世界自然遺産の島・奄美大島で、手つかずのサンゴ礁とウミガメに出会う。島グルメも堪能できるのんびりプラン。', '鹿児島・奄美大島', 'BEGINNER', 8, 42000, 2, 0, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '奄美大島 大物狙いドリフトダイブ', '潮の速い外洋ポイントでバラクーダ・カンパチの大群を狙うアドレナリン全開ツアー。ドリフト経験者限定。', '鹿児島・奄美大島', 'ADVANCED', 4, 28000, 1, 50, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '串本 サンゴの楽園ダイブ', '本州最南端・串本で世界最北のテーブルサンゴ群落を堪能。大阪から日帰りOK。温泉付きプランも。', '和歌山・串本', 'BEGINNER', 8, 15000, 1, 0, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '白浜 レックダイビング＆温泉', '沈船探検ダイブと白浜温泉を楽しむ贅沢ツアー。沈船に棲みつく魚たちの世界は必見。ダイブ後は温泉で疲れを癒す。', '和歌山・白浜', 'INTERMEDIATE', 6, 19000, 1, 10, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '小笠原 ボニンブルーの海 5日間', '東京から船で24時間の世界自然遺産・小笠原。シロワニ、イルカ、巨大マグロの群れなど本土では見られない海中世界。一生に一度の体験。', '東京・小笠原', 'ADVANCED', 4, 198000, 5, 30, 'Y');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '柏島 マクロ天国ダイブ 2日間', '日本屈指の透明度を誇る高知・柏島でマクロ生物三昧。カエルアンコウ、ピグミーシーホースなどレア種のオンパレード。', '高知・柏島', 'BEGINNER', 6, 38000, 2, 0, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '初島 アイランドダイブ日帰り', '熱海から船で30分の離島・初島。黒潮の恩恵で魚影抜群。ダイブの後は島カフェでゆったり。気軽な離島ダイブ体験。', '静岡・伊豆', 'INTERMEDIATE', 6, 20000, 1, 10, 'N');
INSERT INTO TOURS (TOUR_ID, TOUR_NAME, DESCRIPTION, AREA, DIFFICULTY, MAX_PARTICIPANTS, BASE_PRICE, DURATION_DAYS, MIN_DIVE_COUNT, FEATURED_FLAG)
VALUES (SEQ_TOURS.NEXTVAL, '沖縄離島ホッピング 5日間', '慶良間・宮古・石垣の3島を巡る究極の沖縄ダイビング旅。各島2ダイブずつ計6ダイブ。宿泊・島間移動費込み。', '沖縄', 'INTERMEDIATE', 6, 168000, 5, 10, 'Y');

-- =====================
-- ツアー - ダイブサイト紐付け
-- =====================
-- ツアー1: 青の洞窟体験 → 青の洞窟, ゴリラチョップ
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (1, 1, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (1, 6, 2);
-- ツアー2: 慶良間ウミガメ → 座間味, アリガーケーブル
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (2, 2, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (2, 8, 2);
-- ツアー3: 石垣マンタ → マンタスクランブル, 米原Wリーフ
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (3, 3, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (3, 11, 2);
-- ツアー4: 与那国 → 海底遺跡
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (4, 4, 1);
-- ツアー5: 伊豆大瀬崎 → 大瀬崎柵下, 大瀬崎外海
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (5, 13, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (5, 14, 2);
-- ツアー6: 屋久島 → 一湊, お宮前
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (6, 19, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (6, 20, 2);
-- ツアー7: 万座ドリームホール → 万座ドリームホール
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (7, 5, 1);
-- ツアー8: ゴリラチョップ体験 → ゴリラチョップ
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (8, 6, 1);
-- ツアー9: 宮古島地形 → 通り池, 魔王の宮殿
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (9, 9, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (9, 10, 2);
-- ツアー10: 久米島 → はての浜沖
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (10, 12, 1);
-- ツアー11: 雲見 → 雲見
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (11, 15, 1);
-- ツアー12: 伊豆海洋公園 → 伊豆海洋公園
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (12, 16, 1);
-- ツアー13: 奄美大島 → 倉崎海岸
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (13, 21, 1);
-- ツアー14: 奄美大島ドリフト → 山本スペシャル
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (14, 22, 1);
-- ツアー15: 串本 → グラスワールド, 住崎
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (15, 23, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (15, 24, 2);
-- ツアー16: 白浜 → 沈船, 沖の島
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (16, 25, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (16, 26, 2);
-- ツアー17: 小笠原 → 閂ロック, マグロ穴
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (17, 27, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (17, 28, 2);
-- ツアー18: 柏島 → 後浜, 竜の浜
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (18, 29, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (18, 30, 2);
-- ツアー19: 初島 → 初島
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (19, 17, 1);
-- ツアー20: 沖縄3島周遊 → 座間味, 魔王の宮殿, マンタスクランブル
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (20, 2, 1);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (20, 10, 2);
INSERT INTO TOUR_DIVE_SITES (TOUR_ID, SITE_ID, DIVE_ORDER) VALUES (20, 3, 3);

-- =====================
-- ツアー - インストラクター紐付け
-- =====================
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (1, 3, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (1, 5, 'SAFETY');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (2, 1, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (3, 8, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (3, 4, 'PHOTOGRAPHER');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (4, 2, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (4, 5, 'SAFETY');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (5, 7, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (6, 1, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (7, 2, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (8, 3, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (9, 6, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (10, 1, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (11, 7, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (12, 4, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (12, 7, 'PHOTOGRAPHER');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (13, 9, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (14, 5, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (15, 10, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (16, 10, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (17, 2, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (17, 5, 'SAFETY');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (18, 9, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (18, 4, 'PHOTOGRAPHER');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (19, 7, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (20, 1, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (20, 6, 'GUIDE');
INSERT INTO TOUR_INSTRUCTORS (TOUR_ID, INSTRUCTOR_ID, ROLE) VALUES (20, 8, 'GUIDE');

-- =====================
-- ツアースケジュール（50件）2026年4月〜9月
-- =====================

-- ツアー1: 青の洞窟体験（7件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-04-11', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-04-18', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-04-25', '09:00', 5, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-05-02', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-05-16', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-06-06', '09:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 1, DATE '2026-07-04', '09:00', 8, 'OPEN');

-- ツアー2: 慶良間ウミガメ（5件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 2, DATE '2026-04-12', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 2, DATE '2026-04-26', '08:00', 3, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 2, DATE '2026-05-10', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 2, DATE '2026-06-07', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 2, DATE '2026-07-12', '08:00', 6, 'OPEN');

-- ツアー3: 石垣マンタ3日間（3件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 3, DATE '2026-05-01', '07:30', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 3, DATE '2026-06-12', '07:30', 4, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 3, DATE '2026-07-24', '07:30', 6, 'OPEN');

-- ツアー4: 与那国（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 4, DATE '2026-05-15', '07:00', 4, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 4, DATE '2026-06-19', '07:00', 4, 'OPEN');

-- ツアー5: 伊豆大瀬崎（5件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 5, DATE '2026-04-05', '07:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 5, DATE '2026-04-19', '07:30', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 5, DATE '2026-05-03', '07:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 5, DATE '2026-05-24', '07:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 5, DATE '2026-06-14', '07:30', 8, 'OPEN');

-- ツアー6: 屋久島（3件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 6, DATE '2026-05-09', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 6, DATE '2026-06-20', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 6, DATE '2026-08-01', '08:00', 6, 'OPEN');

-- ツアー7: 万座ドリームホール（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 7, DATE '2026-04-19', '08:30', 4, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 7, DATE '2026-05-17', '08:30', 4, 'OPEN');

-- ツアー8: ゴリラチョップ体験（4件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 8, DATE '2026-04-12', '10:00', 10, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 8, DATE '2026-04-29', '10:00', 10, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 8, DATE '2026-05-09', '10:00', 10, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 8, DATE '2026-06-13', '10:00', 10, 'OPEN');

-- ツアー9: 宮古島地形（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 9, DATE '2026-05-22', '07:30', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 9, DATE '2026-07-10', '07:30', 6, 'OPEN');

-- ツアー10: 久米島（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 10, DATE '2026-05-30', '08:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 10, DATE '2026-07-18', '08:30', 8, 'OPEN');

-- ツアー11: 雲見（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 11, DATE '2026-04-26', '07:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 11, DATE '2026-05-31', '07:00', 6, 'OPEN');

-- ツアー12: 伊豆海洋公園マクロ（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 12, DATE '2026-04-05', '08:00', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 12, DATE '2026-05-10', '08:00', 8, 'OPEN');

-- ツアー13: 奄美サンゴ（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 13, DATE '2026-05-16', '08:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 13, DATE '2026-06-27', '08:30', 8, 'OPEN');

-- ツアー14: 奄美ドリフト（1件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 14, DATE '2026-06-06', '07:00', 4, 'OPEN');

-- ツアー15: 串本（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 15, DATE '2026-04-18', '08:30', 8, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 15, DATE '2026-05-23', '08:30', 8, 'OPEN');

-- ツアー16: 白浜レック（1件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 16, DATE '2026-05-09', '08:00', 6, 'OPEN');

-- ツアー17: 小笠原（1件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 17, DATE '2026-06-01', '07:00', 4, 'OPEN');

-- ツアー18: 柏島（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 18, DATE '2026-05-23', '08:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 18, DATE '2026-07-04', '08:00', 6, 'OPEN');

-- ツアー19: 初島（1件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 19, DATE '2026-05-03', '07:30', 6, 'OPEN');

-- ツアー20: 沖縄3島周遊（2件）
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 20, DATE '2026-06-15', '07:00', 6, 'OPEN');
INSERT INTO TOUR_SCHEDULES (SCHEDULE_ID, TOUR_ID, TOUR_DATE, START_TIME, REMAINING_SEATS, STATUS) VALUES (SEQ_TOUR_SCHEDULES.NEXTVAL, 20, DATE '2026-08-10', '07:00', 6, 'OPEN');

-- =====================
-- ニュース（10件）
-- =====================
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '2026年ゴールデンウィーク特別ツアー受付開始！',
        '今年のGWは沖縄でダイビング！青の洞窟体験ダイビングと慶良間ファンダイブの特別プランをご用意しました。早期予約で10%OFF。4月15日までのご予約が対象です。',
        'CAMPAIGN', DATE '2026-03-01');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '石垣島マンタツアー 2026シーズン開始',
        '今年もマンタシーズンがやってきました！5月から10月まで、マンタスクランブルで大迫力のマンタウォッチングをお楽しみください。昨年は遭遇率95%でした。',
        'TOUR', DATE '2026-03-05');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '新インストラクター4名着任のお知らせ',
        '4月より島袋翔、黒潮あかり、磯辺大地、南風まりなの4名が新たに着任します。レスキュー、ナイトダイブ、体験ダイビング、マンタガイドの各分野のスペシャリストです。',
        'INFO', DATE '2026-03-10');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, 'サイトリニューアルのお知らせ',
        'ウェブサイトをリニューアルしました。ツアーの検索・予約がより便利になりました。マイページからダイビングログの記録もできます。ぜひご利用ください。',
        'INFO', DATE '2026-03-15');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '小笠原ツアー 2026年度 受付開始',
        '世界自然遺産・小笠原諸島でのダイビングツアーの予約受付を開始しました。5日間のスペシャルツアーで、シロワニやイルカとの感動的な出会いが待っています。定員4名の少人数制。',
        'TOUR', DATE '2026-03-18');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '春の体験ダイビングキャンペーン',
        '3月〜5月限定！体験ダイビング初回20%OFF。沖縄・本部のゴリラチョップは穏やかなビーチエントリーで初心者にぴったり。水中写真のプレゼント付き。',
        'CAMPAIGN', DATE '2026-03-20');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '宮古島地形ダイブツアー 新コース追加',
        '大好評の宮古島地形ダイブツアーに「アントニオ・ガウディ」コースを追加しました。通り池、魔王の宮殿と合わせて3大地形ポイントを3日間で完全制覇。',
        'TOUR', DATE '2026-03-22');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '安全ダイビング講習会のご案内',
        '4月10日（土）にオンライン安全ダイビング講習会を開催します。レスキューインストラクター島袋が、安全なダイビングのための知識と技術をわかりやすく解説。参加費無料。',
        'INFO', DATE '2026-03-25');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '梅雨明け特別プラン 予約受付中',
        '7月の沖縄は梅雨明けのベストシーズン！慶良間・石垣・宮古の各ツアーで梅雨明け特別割引を実施。最大15%OFFのチャンスをお見逃しなく。',
        'CAMPAIGN', DATE '2026-03-28');
INSERT INTO NEWS (NEWS_ID, TITLE, CONTENT, CATEGORY, PUBLISH_DATE)
VALUES (SEQ_NEWS.NEXTVAL, '沖縄離島ホッピングツアー 新登場',
        '慶良間・宮古・石垣の3島を巡る究極のダイビング旅が登場！各島2ダイブずつ計6ダイブ、島間の移動費と宿泊がすべてパッケージに含まれたお得なツアーです。',
        'TOUR', DATE '2026-03-30');

-- =====================
-- テスト用顧客（10名、パスワード: test1234）
-- =====================
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'tanaka@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '田中', '太郎', 'タナカ', 'タロウ', '090-1234-5678', DATE '1990-05-15', 'PADI アドバンスド・オープンウォーター', 35, '田中花子 090-1111-2222');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'suzuki@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '鈴木', '花子', 'スズキ', 'ハナコ', '080-9876-5432', DATE '1995-08-20', 'PADI オープンウォーター', 8, '鈴木一郎 080-3333-4444');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'yamada@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '山田', '健一', 'ヤマダ', 'ケンイチ', '070-1111-2222', DATE '1985-01-10', 'PADI レスキューダイバー', 120, '山田美紀 070-5555-6666');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'sato@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '佐藤', 'めぐみ', 'サトウ', 'メグミ', '090-3333-4444', DATE '1992-11-30', 'PADI ダイブマスター', 250, '佐藤洋平 090-7777-8888');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'takahashi@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '高橋', '翔太', 'タカハシ', 'ショウタ', '080-5555-6666', DATE '1998-03-25', 'NONE', 0, '高橋良子 080-9999-0000');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'watanabe@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '渡辺', '美月', 'ワタナベ', 'ミヅキ', '090-7777-8888', DATE '1988-07-07', 'PADI アドバンスド・オープンウォーター', 45, '渡辺大輔 090-1234-0000');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'ito@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '伊藤', '大輔', 'イトウ', 'ダイスケ', '070-9999-0000', DATE '1993-12-01', 'PADI オープンウォーター', 15, '伊藤恵子 070-4444-5555');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'nakamura@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '中村', '陽子', 'ナカムラ', 'ヨウコ', '080-2222-3333', DATE '1980-09-14', 'PADI レスキューダイバー', 80, '中村正義 080-6666-7777');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'kobayashi@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '小林', '遼', 'コバヤシ', 'リョウ', '090-4444-5555', DATE '2000-04-22', 'NONE', 0, '小林幸恵 090-8888-9999');
INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, PASSWORD_HASH, LAST_NAME, FIRST_NAME, LAST_NAME_KANA, FIRST_NAME_KANA, PHONE, BIRTH_DATE, LICENSE_LEVEL, DIVE_COUNT, EMERGENCY_CONTACT)
VALUES (SEQ_CUSTOMERS.NEXTVAL, 'yoshida@example.com',
        DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW('test1234', 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256),
        '吉田', 'さくら', 'ヨシダ', 'サクラ', '070-6666-7777', DATE '1996-06-18', 'PADI アドバンスド・オープンウォーター', 60, '吉田雄太 070-2222-3333');

COMMIT;
